### ISSUE TITLE
Add Support for `Seam-Workspace` header

### ISSUE THREAD

**Issue by seveibar** [seamapi/seamapi-javascript#1]
The `Seam-Workspace` header is required for multi-workspace API keys (currently unsupported) and session-based API keys when we dogfood the api on our dashboard.

The `Seam-Workspace` header is set to the `workspace_id` on which the action/endpoint should be executed against.

I see two ways to implement this (I think we can probably do both)
* Set Seam-Workspace as part of the context e.g. `seam.setWorkspace(workspace_id)`
* Allow `workspace_id` or possibly the a more unique `target_workspace_id` to be provided as the body to every request, but then convert it into a header and remove from the body. We could also adapt the seam api to accept `Seam-Target-Workspace` to make keep things clear- although this isn't a common path feature so it's probably fine.

Workaround: I believe we can access the axios client directly and add the header to the custom instance. So this is not super important to address in the short term.

**Comment by codetheweb** [comment]
I believe this is closed by https://github.com/seamapi/seamapi-javascript/commit/d51f40b2118d38703ab45aabb2fcc30fa262266e.
